// Copyright (c) 2026 https://github.com/copper10bull-lgtm
// SPDX-License-Identifier: Apache-2.0
#pragma once
#include "common.h"

enum StringId {
    STR_MENU_FILE, STR_MENU_NEW, STR_MENU_OPEN, STR_MENU_SAVE, STR_MENU_SAVEAS,
    STR_MENU_CLOSETAB, STR_MENU_EXIT, STR_MENU_HASH, STR_MENU_HASH_MD5, STR_MENU_HASH_SHA1,
    STR_MENU_HASH_SHA256, STR_MENU_EDIT, STR_MENU_UNDO, STR_MENU_CUT, STR_MENU_COPY,
    STR_MENU_PASTE, STR_MENU_SELECTALL, STR_MENU_FIND,
    STR_MENU_VIEW, STR_MENU_DARKTHEME, STR_MENU_FONT, STR_MENU_HEXMODE,
    STR_MENU_LANGUAGE, STR_MENU_LANG_EN, STR_MENU_LANG_RU,
    STR_MENU_CONTEXTMENU_ADD, STR_MENU_CONTEXTMENU_REMOVE,
    STR_UNTITLED, STR_LOADING,
    STR_ERROR_OPEN_FILE, STR_ERROR_OPEN_CMDLINE, STR_FILE_TOO_BIG, STR_CLOSE_SAVE_PROMPT,
    STR_EXIT_SAVE_PROMPT, STR_STATUS_LINE_COL, STR_STATUS_UTF8_SIZE, STR_TITLE,
    STR_LANGUAGE_SELECT, STR_LANGUAGE_ENGLISH, STR_LANGUAGE_RUSSIAN, STR_HASH_TITLE,
    STR_HASH_EMPTY, STR_CONTEXTMENU_ADDED, STR_CONTEXTMENU_REMOVED, STR_CONTEXTMENU_ADD_FAIL,
    STR_CONTEXTMENU_REMOVE_FAIL, STR_HEX_WARNING, STR_MSFTEDIT_NOTFOUND, STR_CREATE_RICHEDIT_FAIL,
    STR_NOT_ENOUGH_MEMORY, STR_ERROR_READ_FILE, STR_HEX_MEMORY_ERROR, STR_HEX_TRUNCATED,
    STR_MENU_ENCODING, STR_ENC_UTF8, STR_ENC_UTF16LE, STR_ENC_UTF16BE,
    STR_ENC_WIN1251, STR_ENC_WIN1252,
    STR_STATUS_ENC_SIZE,
    STR_FIND_TITLE, STR_FIND_WHAT, STR_FIND_NOT_FOUND,
    STR_COUNT
};

extern const WCHAR* strings[2][STR_COUNT];
extern int currentLang;

const WCHAR* GetStr(enum StringId id);